//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Database.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] _10_Hram_imperatora_Meydzi_e1528833104117 {
            get {
                object obj = ResourceManager.GetObject("_10_Hram_imperatora_Meydzi_e1528833104117", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] _12_Perekrestok_na_Sibuya_e1528915241354 {
            get {
                object obj = ResourceManager.GetObject("_12_Perekrestok_na_Sibuya_e1528915241354", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] _2_Rayon_Asakusa_e1528832886299 {
            get {
                object obj = ResourceManager.GetObject("_2_Rayon_Asakusa_e1528832886299", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] _2_Zotoy_pavilon_e1528829317599 {
            get {
                object obj = ResourceManager.GetObject("_2_Zotoy_pavilon_e1528829317599", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] _22_Kyoto_International_Manga_Museum {
            get {
                object obj = ResourceManager.GetObject("_22_Kyoto_International_Manga_Museum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] _3_Bambukovaya_roshha_Sagano_e1528829507639 {
            get {
                object obj = ResourceManager.GetObject("_3_Bambukovaya_roshha_Sagano_e1528829507639", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] _4_Hram_Kiyomidzue1528829737668 {
            get {
                object obj = ResourceManager.GetObject("_4_Hram_Kiyomidzue1528829737668", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] _4_Outside_Akihabara_Station_e1528841551644 {
            get {
                object obj = ResourceManager.GetObject("_4_Outside_Akihabara_Station_e1528841551644", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] _8_Sad_Happoen_e1528833047691 {
            get {
                object obj = ResourceManager.GetObject("_8_Sad_Happoen_e1528833047691", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] anime_shop {
            get {
                object obj = ResourceManager.GetObject("anime_shop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] arctikum_museum {
            get {
                object obj = ResourceManager.GetObject("arctikum_museum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] bc1 {
            get {
                object obj = ResourceManager.GetObject("bc1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] bc2 {
            get {
                object obj = ResourceManager.GetObject("bc2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] bc3 {
            get {
                object obj = ResourceManager.GetObject("bc3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] franciscan_monastery {
            get {
                object obj = ResourceManager.GetObject("franciscan_monastery", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] gp1 {
            get {
                object obj = ResourceManager.GetObject("gp1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] gp2 {
            get {
                object obj = ResourceManager.GetObject("gp2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] gp3 {
            get {
                object obj = ResourceManager.GetObject("gp3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Griffith_Park_Los_Angeles_Hiking_Track {
            get {
                object obj = ResourceManager.GetObject("Griffith_Park_Los_Angeles_Hiking_Track", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Healing_springs_in_Terpenye {
            get {
                object obj = ResourceManager.GetObject("Healing_springs_in_Terpenye", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] history_of_japan_arts_culture_byoudin_temple_kyoto_tokyo_weekender {
            get {
                object obj = ResourceManager.GetObject("history_of_japan_arts_culture_byoudin_temple_kyoto_tokyo_weekender", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] holly1 {
            get {
                object obj = ResourceManager.GetObject("holly1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] holly2 {
            get {
                object obj = ResourceManager.GetObject("holly2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] holly3 {
            get {
                object obj = ResourceManager.GetObject("holly3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Hollywood_Sign_Zuschnitt_801x501 {
            get {
                object obj = ResourceManager.GetObject("Hollywood_Sign_Zuschnitt_801x501", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ice_hotel {
            get {
                object obj = ResourceManager.GetObject("ice_hotel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] international_spy_museum {
            get {
                object obj = ResourceManager.GetObject("international_spy_museum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] jefferson_memorial {
            get {
                object obj = ResourceManager.GetObject("jefferson_memorial", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] kreeger_museum {
            get {
                object obj = ResourceManager.GetObject("kreeger_museum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] kyoto_national_municipal_museum {
            get {
                object obj = ResourceManager.GetObject("kyoto_national_municipal_museum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] kyoto_university_of_art {
            get {
                object obj = ResourceManager.GetObject("kyoto_university_of_art", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] kyoto1 {
            get {
                object obj = ResourceManager.GetObject("kyoto1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] La_convention_center {
            get {
                object obj = ResourceManager.GetObject("La_convention_center", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] La1 {
            get {
                object obj = ResourceManager.GetObject("La1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] lapland {
            get {
                object obj = ResourceManager.GetObject("lapland", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] library_of_congress {
            get {
                object obj = ResourceManager.GetObject("library_of_congress", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] lincoln_memorial {
            get {
                object obj = ResourceManager.GetObject("lincoln_memorial", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] lumi_linna {
            get {
                object obj = ResourceManager.GetObject("lumi_linna", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] madame_tussauds_hollywood {
            get {
                object obj = ResourceManager.GetObject("madame_tussauds_hollywood", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] mt1 {
            get {
                object obj = ResourceManager.GetObject("mt1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] mt2 {
            get {
                object obj = ResourceManager.GetObject("mt2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] mt3 {
            get {
                object obj = ResourceManager.GetObject("mt3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] national_air_and_space_museum {
            get {
                object obj = ResourceManager.GetObject("national_air_and_space_museum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] national_alley {
            get {
                object obj = ResourceManager.GetObject("national_alley", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] pilke_museum {
            get {
                object obj = ResourceManager.GetObject("pilke_museum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ranua_zoo {
            get {
                object obj = ResourceManager.GetObject("ranua_zoo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] rock_creek_park {
            get {
                object obj = ResourceManager.GetObject("rock_creek_park", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] santa_klaus_village {
            get {
                object obj = ResourceManager.GetObject("santa_klaus_village", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Santa_park {
            get {
                object obj = ResourceManager.GetObject("Santa_park", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Santa_park2 {
            get {
                object obj = ResourceManager.GetObject("Santa_park2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] sech {
            get {
                object obj = ResourceManager.GetObject("sech", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] siida {
            get {
                object obj = ResourceManager.GetObject("siida", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] smithsonian_national_museum_of_natural_history {
            get {
                object obj = ResourceManager.GetObject("smithsonian_national_museum_of_natural_history", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] The_Broad_Contemporary_Art_Museum_in_Downtown_Los_Angeles {
            get {
                object obj = ResourceManager.GetObject("The_Broad_Contemporary_Art_Museum_in_Downtown_Los_Angeles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] the_national_art_center_tokyo_t2 {
            get {
                object obj = ResourceManager.GetObject("the_national_art_center_tokyo_t2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] united_states_capitol {
            get {
                object obj = ResourceManager.GetObject("united_states_capitol", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] usadba_popova {
            get {
                object obj = ResourceManager.GetObject("usadba_popova", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] vasilievka_zoo {
            get {
                object obj = ResourceManager.GetObject("vasilievka_zoo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] warner_bros {
            get {
                object obj = ResourceManager.GetObject("warner_bros", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] washington_monument {
            get {
                object obj = ResourceManager.GetObject("washington_monument", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] washington_national_cathedral {
            get {
                object obj = ResourceManager.GetObject("washington_national_cathedral", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Washington1 {
            get {
                object obj = ResourceManager.GetObject("Washington1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] wb1 {
            get {
                object obj = ResourceManager.GetObject("wb1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] wb2 {
            get {
                object obj = ResourceManager.GetObject("wb2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] wb3 {
            get {
                object obj = ResourceManager.GetObject("wb3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] white_house {
            get {
                object obj = ResourceManager.GetObject("white_house", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] yatkankyuntyllya_bridge {
            get {
                object obj = ResourceManager.GetObject("yatkankyuntyllya_bridge", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] zaporizhzhya_2 {
            get {
                object obj = ResourceManager.GetObject("zaporizhzhya_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
